---
version: 2

env:
  - GO111MODULE=on
  - LINUXBENCH_CFG=/etc/linux-bench/cfg

builds:
  - main: .
    binary: linux-bench
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - "-X github.com/aquasecurity/linux-bench/root.cfgDir={{.Env.LINUXBENCH_CFG}}"
# Archive customization
archives:
  - id: compress
    formats: [tar.gz]
    name_template: "{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}"
    files:
      - "cfg/**/*"
nfpms:
  - vendor: Aqua Security
    description: "Linux-bench checks whether a Linux server according to security best practices as defined in the CIS Distribution-Independent Linux Benchmark"
    license: Apache-2.0
    homepage: https://github.com/aquasecurity/linux-bench
    contents:
      - src: "cfg/**/*"
        dst: "/etc/linux-bench/cfg"
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
    formats:
      - deb
      - rpm
