---
apiVersion: batch/v1
kind: Job
metadata:
  name: linux-bench
spec:
  template:
    spec:
      hostPID: true
      containers:
        - name: linux-bench
          # Push the image to your ECR and then refer to it here
          # image: <ID.dkr.ecr.region.amazonaws.com/aquasec/linux-bench:ref>
          image: ttousai/linux-bench
          command:
            [
              "linux-bench",
              "-v3",
              "--version",
              "bottlerocket",
              "-c3.1.1a",
            ]
          volumeMounts:
            - name: apiclient
              mountPath: /usr/bin/apiclient
              readOnly: true
            - name: apiserver-socket
              mountPath: /run/api.sock
          securityContext:
            seLinuxOptions:
              level: s0
              role: system_r
              type: control_t
              user: system_u
      restartPolicy: Never
      volumes:
        - name: apiclient
          hostPath:
            path: /usr/bin/apiclient
            type: File
        - name: apiserver-socket
          hostPath:
            path: /run/api.sock
            type: Socket
